use testdb;
create table if not exists table1 (canon VARCHAR(256), symbol VARCHAR(256), PRIMARY KEY (symbol), INDEX(canon)) ENGINE = MYISAM;
insert into table1 values("canonA", "canonA");
insert into table1 values("canonA", "symbolA1");
insert into table1 values("canonA", "symbolA2");
insert into table1 values("canonA", "symbolA3");
insert into table1 values("canonB", "canonB");
insert into table1 values("canonB", "symbolB1");
insert into table1 values("canonB", "symbolB2");
insert into table1 values("canonB", "symbolB3");
